{% set name = "phispy" %}
{% set ucname = "PhiSpy" %}
{% set version = "4.2.18" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ ucname }}-{{ version }}.tar.gz"
  sha256: "0d2ac197f6cc2e4e365a23a0ae1c64b35e96431b77aad9a78fbaec3fc6fea09c"

build:
  number: 0
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - biopython >=1.74
    - numpy >=1.17.0
    - python
    - hmmer
    - scikit-learn >=0.21.3
    - bcbio-gff

test:
  imports:
    - PhiSpyModules
  commands:
    - PhiSpy.py -v

about:
  home: "https://github.com/linsalrob/PhiSpy"
  license: MIT
  license_family: MIT
  summary: "Prophage finder using multiple metrics"
  doc_url: "https://github.com/linsalrob/PhiSpy/blob/master/README.md"
  dev_url: "https://github.com/linsalrob/PhiSpy/"

extra:
  recipe-maintainers:
    - linsalrob
  identifiers:
    - doi:10.5281/zenodo.3475717
